# configuration pilfered from https://circleci.com/docs/2.0/language-android/
version: 2

jobs:
  build:
    environment:
      TARGET_SDK_VERSION: 25

    # https://circleci.com/docs/2.0/configuration-reference/#docker--machine-executor
    docker:
      - image: bitriseio/docker-android:latest
      - image: ghost:1-alpine   # test against latest 1.x version of Ghost

    steps:
      # adapted from https://github.com/nenick/android-circleci-2.0/blob/master/circle.yml
      # setup emulator first so it can launch in the background while we run build and unit tests
      - run:
          name: Setup emulator
          command: |
            SYSTEM_IMAGE="system-images;android-25;google_apis;armeabi-v7a"
            echo "no" | avdmanager create avd -n test -k "${SYSTEM_IMAGE}"

      - run:
          name: Launch emulator
          command: /opt/android-sdk-linux/emulator/emulator -avd test -noaudio -no-boot-anim -no-window -accel on
          background: true

      # https://circleci.com/docs/2.0/configuration-reference/#checkout
      - checkout

      # https://circleci.com/docs/2.0/configuration-reference/#restore_cache
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies

      # https://circleci.com/docs/2.0/configuration-reference/#save_cache
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

      - run:
          name: Build Debug APK  # not a release build since Fabric API keys are not available in CI
          command: ./gradlew assembleDebug -PdisablePreDex --console=plain

      - run:
          name: Setup Ghost
          command: curl -vvvv --fail -d 'setup[0][name]=User' -d 'setup[0][email]=user@example.com' -d 'setup[0][password]=randomtestpwd' -d 'setup[0][blogTitle]=My Blog' http://localhost:2368/ghost/api/v0.1/authentication/setup/

      - run:
          name: Run unit tests
          command: ./gradlew testDebug -PdisablePreDex --console=plain

      - run:
          name: Wait for emulator
          command: |
            ./.circleci/android-wait-for-boot.sh
            # unlock the emulator screen
            sleep 30
            adb shell input keyevent 82

      - run:
          name: Run end-to-end tests
          command: ./gradlew connectedAndroidTest -PdisablePreDex --console=plain

      # https://circleci.com/docs/2.0/configuration-reference/#store_artifacts
      - store_artifacts:
          path: app/build/reports
          destination: reports

      # https://circleci.com/docs/2.0/configuration-reference/#store_test_results
      - store_test_results:
          path: app/build/test-results
